from django.urls import path, include
from rest_framework.routers import SimpleRouter
from .views import UserViewSet

"""
URL Configuration for User-Related Actions

This module sets up the routing for user-related actions using Django Rest Framework's SimpleRouter
and a ViewSet. The SimpleRouter automatically generates RESTful routes for the UserViewSet,
allowing for a clean and organized structure.

Routes generated by the SimpleRouter include:
- POST /register/ - Register a new user (custom action defined in UserViewSet)
- POST /login/ - Log in a user and return an authentication token (custom action defined in UserViewSet)
- POST /logout/ - Log out a user by deleting their authentication token (custom action defined in UserViewSet)
- GET /{pk}/ - Retrieve a specific user by ID (default action from ViewSet)
- PUT /{pk}/ - Replace a specific user with new data (default action from ViewSet)
- PATCH /{pk}/ - Partially update a specific user (default action from ViewSet)
"""

# SimpleRouter can autogenerate URIs for a given ViewSet
router = SimpleRouter()
router.register(r'', UserViewSet, basename='user')

urlpatterns = [
    # Include the auto-generated routes from the router
    path('', include(router.urls))
]
