# Generated by Django 4.1.6 on 2024-08-13 22:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Problem ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lc_id', models.CharField(max_length=100, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=7)),
                ('category', models.CharField(choices=[('arrays-hashing', 'Arrays and Hashing'), ('two-pointers', 'Two Pointers'), ('sliding-window', 'Sliding Window'), ('stack', 'Stack'), ('binary-search', 'Binary Search'), ('linked-list', 'Linked List'), ('trees', 'Trees'), ('heap-pq', 'Heap / Priority Queue'), ('backtracking', 'Backtracking'), ('tries', 'Tries'), ('graphs', 'Graphs'), ('advanced-graphs', 'Advanced Graphs'), ('dynamic-1d', '1-D Dynamic Programming'), ('dynamic-2d', '2-D Dynamic Programming'), ('greedy', 'Greedy'), ('intervals', 'Intervals'), ('math-geom', 'Math and Geometry'), ('bit-manip', 'Bit Manipulation')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Duration (minutes)')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Score')),
                ('num_attempts', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Number of attempts until completed')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem', verbose_name='Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Problem Attempt',
                'verbose_name_plural': 'Problem Attempts',
                'unique_together': {('user', 'problem', 'timestamp')},
            },
        ),
    ]
